Algoritmo "nomeeidade"

Var
name1, name2:caractere
idad1, idad2, mult:real


Inicio
escreval("Insira o primeiro nome")
leia(name1)
escreval("Insira o segundo nome")
leia(name2)
escreval("Insira a primeira idade")
leia(idad1)
escreval("Insira a segunda idade")
leia(idad2)

mult <- (idad1 * idad2);

escreval("A multiplicacao das idades de ",name1," e ",name2," e igual a ",mult)


Fimalgoritmo
